### ISSUE TITLE
startup us not working 

### ISSUE THREAD

**Issue by rnea7840** [GoogleCloudPlatform/deploystack-etl-pipeline#2]
with google_project_iam_member.composerAgent,
│   on main.tf line 93, in resource "google_project_iam_member" "composerAgent":
│   93: resource "google_project_iam_member" "composerAgent" {
│
╵
╷
│ Error: Error creating Dataset: googleapi: Error 409: Already Exists: Dataset datapipe-369706:average_weather, duplicate
│
│   with google_bigquery_dataset.weather_dataset,
│   on main.tf line 124, in resource "google_bigquery_dataset" "weather_dataset":
│  124: resource "google_bigquery_dataset" "weather_dataset" {
│
╵
╷
│ Error: googleapi: Error 409: Your previous request to create the named bucket succeeded and you already own it., conflict
│
│   with google_storage_bucket.pipeline_files,
│   on main.tf line 175, in resource "google_storage_bucket" "pipeline_files":
│  175: resource "google_storage_bucket" "pipeline_files" {
│
╵

An error occured collecting the necessary information to run your Deploystack
application. Please try again.

**Comment by rnea7840** [comment]
have trouble starting pipeline

**Comment by rnea7840** [comment]
error 2: Warning: Value for undeclared variable
│
│ The root module does not declare a variable named "stack_name" but a value was found in
│ file "terraform.tfvars". If you meant to use this value, add a "variable" block to the
│ configuration.
│
│ To silence these warnings, use TF_VAR_... environment variables to provide certain "global"
│ settings to all configurations in your organization. To reduce the verbosity of these
│ warnings, use the -compact-warnings option.
╵
╷
│ Error: Request `Create IAM Members roles/composer.ServiceAgentV2Ext serviceAccount:service-demopipe@cloudcomposer-accounts.iam.gserviceaccount.com for project "demopipe"` returned error: Batch request and retried single request "Create IAM Members roles/composer.ServiceAgentV2Ext serviceAccount:service-demopipe@cloudcomposer-accounts.iam.gserviceaccount.com for project \"demopipe\"" both failed. Final error: Error applying IAM policy for project "demopipe": Error setting IAM policy for project "demopipe": googleapi: Error 400: Service account service-demopipe@cloudcomposer-accounts.iam.gserviceaccount.com does not exist., badRequest
│
│   with google_project_iam_member.composerAgent,
│   on main.tf line 93, in resource "google_project_iam_member" "composerAgent":
│   93: resource "google_project_iam_member" "composerAgent" {
│
╵

An error occured collecting the necessary information to run your Deploystack
application. Please try again.

**Comment by aliciawilliams** [comment]
I recommend starting a fresh, new project and trying again, or using ```terraform destroy``` command within the current project (being careful if there are other resources in this project, of course) to bring down all resources previously created and then starting over. This is because it looks like two of the errors were around creating resources that already existed. 

The warning about the variable called ```stack_name``` is nothing you need to worry about and will not cause issues.

I did test the code as-is I was able to bring up this deploystack in a fresh project. Keep me posted if these suggestions do not resolve your issue.
