### ISSUE TITLE
Airflow version outdated

### ISSUE THREAD

**Issue by louisphilip** [GoogleCloudPlatform/deploystack-etl-pipeline#4]
![Screenshot 2023-08-23 at 20 12 58](https://github.com/GoogleCloudPlatform/deploystack-etl-pipeline/assets/72431908/6794c09a-339c-4084-945d-02db81ea2e81)

**Comment by aliciawilliams** [comment]
Just updated with PR: https://github.com/GoogleCloudPlatform/deploystack-etl-pipeline/pull/7
